export type LineageRank =
  | "mythic"
  | "origin"
  | "khan"
  | "great-khan"
  | "prince"
  | "empire-founder"
  | "revival"
  | "final-head";

export type LineagePerson = {
  id: string;
  parentIds: string[];
  name: {
    mn: string;
    en: string;
  };
  title: string;
  years: string;
  reign?: string;
  rank: LineageRank;
  branch: string;
  bio: string;
  achievements: string[];
  capital: {
    name: string;
    coordinates: [number, number];
  };
};

// Тайлбар: Алтан ургийн бүрэн угсаа хэдэн зуун хүнийг хамардаг.
// Энэ mock нь visual tree-д тохируулахын тулд гол шугамуудыг төвлөрүүлсэн:
// домогт өвөг -> Боржигин холбоос -> Чингис хааны дөрвөн хүү ->
// Зүч, Цагадай, Өгэдэй, Тулуйн гол салбарууд -> Даян хааны сэргэлт ->
// Лигдэн хаан болон 1924 он хүртэлх дөрвөн аймгийн төлөөлөх төгсгөлийн толгой нар.
export const altanUragPeople: LineagePerson[] = [
  {
    id: "borte-chino",
    parentIds: [],
    name: { mn: "Бөртэ Чоно", en: "Borte Chino" },
    title: "Монголчуудын домогт дээд өвөг",
    years: "ойролцоо VIII зуун",
    rank: "mythic",
    branch: "Домогт язгуур",
    bio: "Монголын нууц товчоонд гардаг Бөртэ Чоно нь Монголчуудын угсаа гарвалын домогт эхлэл хэмээн дурсагддаг.",
    achievements: [
      "Монгол угсааны домогт эхлэлийг төлөөлдөг",
      "Алтан ургийн түүхэн ой санамжийн хамгийн эртний дүр",
    ],
    capital: { name: "Бурхан Халдун орчим", coordinates: [108.8, 48.7] },
  },
  {
    id: "gua-maral",
    parentIds: ["borte-chino"],
    name: { mn: "Гуа Марал", en: "Gua Maral" },
    title: "Домогт эх",
    years: "ойролцоо VIII зуун",
    rank: "mythic",
    branch: "Домогт язгуур",
    bio: "Бөртэ Чонотой хамт тэнгис далайг гэтэлж ирсэн хэмээн домогт өгүүлэгддэг эх дүр.",
    achievements: ["Монгол угсааны эхлэл домогт холбогдсон", "Алтан ургийн эхийн шугамын бэлгэдэл болсон"],
    capital: { name: "Онон-Бурхан Халдун", coordinates: [109.2, 48.6] },
  },
  {
    id: "batachikhan",
    parentIds: ["gua-maral"],
    name: { mn: "Батцагаан", en: "Batachikhan" },
    title: "Домогт залгамжлагч",
    years: "ойролцоо IX зуун",
    rank: "mythic",
    branch: "Домогт язгуур",
    bio: "Бөртэ Чоно, Гуа Маралын дараах эртний угсааны залгамжлагч хэмээн сурвалжид нэрлэгддэг.",
    achievements: ["Эртний Монгол угсааны холбоос болсон"],
    capital: { name: "Хэнтийн нуруу", coordinates: [109.6, 48.3] },
  },
  {
    id: "tamacha",
    parentIds: ["batachikhan"],
    name: { mn: "Тамача", en: "Tamacha" },
    title: "Эртний өвөг",
    years: "ойролцоо IX зуун",
    rank: "mythic",
    branch: "Домогт язгуур",
    bio: "Алтан ургийн өмнөх домогт үеийн залгамж холбоос.",
    achievements: ["Боржигины өмнөх угсааны гинжин холбоонд багтсан"],
    capital: { name: "Онон голын сав", coordinates: [110.1, 48.4] },
  },
  {
    id: "qorichar",
    parentIds: ["tamacha"],
    name: { mn: "Хоричар мэргэн", en: "Qorichar Mergen" },
    title: "Домогт мэргэн өвөг",
    years: "ойролцоо IX-X зуун",
    rank: "mythic",
    branch: "Домогт язгуур",
    bio: "Мэргэн хэмээх тодотголтойгоор уламжлагдсан эртний өвөг.",
    achievements: ["Мэргэн овогтны нэр хүндийг илтгэсэн"],
    capital: { name: "Онон-Хэрлэнгийн тал", coordinates: [110.2, 48.1] },
  },
  {
    id: "torogolchjin",
    parentIds: ["qorichar"],
    name: { mn: "Торголжин баян", en: "Torogolchjin Bayan" },
    title: "Баян язгууртан өвөг",
    years: "ойролцоо X зуун",
    rank: "origin",
    branch: "Боржигины өмнөх холбоос",
    bio: "Добун мэргэний эцэг хэмээн уламжлагдах, Боржигины эхлэлтэй холбогдох чухал өвөг.",
    achievements: ["Добун мэргэн, Алун гуагийн үе рүү угсааг холбосон"],
    capital: { name: "Хэнтий орчим", coordinates: [109.9, 48.0] },
  },
  {
    id: "dobun-mergen",
    parentIds: ["torogolchjin"],
    name: { mn: "Добун мэргэн", en: "Dobun Mergen" },
    title: "Алун гуагийн нөхөр",
    years: "ойролцоо X зуун",
    rank: "origin",
    branch: "Боржигины эхлэл",
    bio: "Алун гуагийн нөхөр, Боржигин угсааны домогт эхлэл рүү шууд холбогдох өвөг.",
    achievements: ["Боржигин угсааны эхэн үеийн гол холбоос болсон"],
    capital: { name: "Онон голын бүс", coordinates: [110.3, 48.3] },
  },
  {
    id: "alan-gua",
    parentIds: ["torogolchjin"],
    name: { mn: "Алун гуа", en: "Alan Gua" },
    title: "Боржигины домогт эх",
    years: "ойролцоо X зуун",
    rank: "origin",
    branch: "Боржигины эхлэл",
    bio: "Алун гуа нь Боржигин овгийн ариун гарал үүслийн домгийн төв дүр бөгөөд Бодончар Мунхагийн эх хэмээн дурсагддаг.",
    achievements: ["Боржигины эхийн шугамын гол дүр", "Алтан ургийн ариун гарал үүслийн домгийг бүрдүүлсэн"],
    capital: { name: "Онон-Бурхан Халдун", coordinates: [109.7, 48.5] },
  },
  {
    id: "bodonchar",
    parentIds: ["dobun-mergen", "alan-gua"],
    name: { mn: "Бодончар Мунхаг", en: "Bodonchar Munkhag" },
    title: "Боржигин овгийн домогт өвөг",
    years: "ойролцоо X зуун",
    rank: "origin",
    branch: "Боржигин",
    bio: "Боржигин овгийн үндсэн өвөг хэмээн дурсагддаг. Чингис хааны угсаа Бодончараас эхтэй гэж Монголын сурвалжууд үздэг.",
    achievements: ["Боржигин овгийн язгуур өвөг болсон", "Их хаадын угсаа залгамжлалын эхлэл болсон"],
    capital: { name: "Онон-Хэрлэнгийн тал нутаг", coordinates: [110.4, 48.6] },
  },
  {
    id: "qaidu",
    parentIds: ["bodonchar"],
    name: { mn: "Хайду", en: "Qaidu" },
    title: "Боржигины эртний ноён",
    years: "ойролцоо XI зуун",
    rank: "khan",
    branch: "Боржигин",
    bio: "Бодончарын дараах үеийн Боржигин ноёдын нэг бөгөөд Хабул хан руу угсааг холбодог гол холбоос.",
    achievements: ["Боржигины ноёдын байр суурийг бэхжүүлсэн"],
    capital: { name: "Хэрлэн-Онон", coordinates: [110.1, 47.9] },
  },
  {
    id: "baishinghor",
    parentIds: ["qaidu"],
    name: { mn: "Байшинхор Догшин", en: "Baishinghor Dogshin" },
    title: "Боржигин ноён",
    years: "ойролцоо XI зуун",
    rank: "khan",
    branch: "Боржигин",
    bio: "Хамаг Монголын хаадын өмнөх Боржигин угсааны төлөөлөгч.",
    achievements: ["Хабул хааны өмнөх угсаа залгамжлалыг хадгалсан"],
    capital: { name: "Хэнтий", coordinates: [109.8, 48.2] },
  },
  {
    id: "tumbinai",
    parentIds: ["baishinghor"],
    name: { mn: "Тумбинай Сэцэн", en: "Tumbinai Setsen" },
    title: "Боржигин сэцэн ноён",
    years: "ойролцоо XI-XII зуун",
    rank: "khan",
    branch: "Боржигин",
    bio: "Хабул хааны эцэг хэмээн дурсагдах, Чингис хааны өмнөх үеийн чухал угсааны холбоос.",
    achievements: ["Хабул хааны угсааны шууд өмнөх үе болсон"],
    capital: { name: "Онон гол", coordinates: [110.0, 48.1] },
  },
  {
    id: "khabul",
    parentIds: ["tumbinai"],
    name: { mn: "Хабул хан", en: "Khabul Khan" },
    title: "Хамаг Монголын хан",
    years: "ойролцоо 1100-1148",
    reign: "ойролцоо XII зуун",
    rank: "khan",
    branch: "Хамаг Монгол",
    bio: "Хамаг Монголын хүчирхэг Боржигин хан. Түүний удирдлага хожим Тэмүжин монгол аймгуудыг нэгтгэх улс төрийн хөрсийг бүрдүүлсэн.",
    achievements: ["Хамаг Монголыг удирдсан", "Боржигины нэр хүндийг өсгөсөн"],
    capital: { name: "Хамаг Монголын нутаг", coordinates: [109.8, 48.1] },
  },
  {
    id: "bartan",
    parentIds: ["khabul"],
    name: { mn: "Бартан баатар", en: "Bartan Baghatur" },
    title: "Боржигин баатар",
    years: "ойролцоо XII зуун",
    rank: "khan",
    branch: "Хамаг Монгол",
    bio: "Хабул ханы хүү, Есүхэй баатрын эцэг. Чингис хааны өвөг эцэг.",
    achievements: ["Есүхэйн угсааны шууд өмнөх үе болсон"],
    capital: { name: "Онон-Хэрлэн", coordinates: [110.5, 48.0] },
  },
  {
    id: "yesugei",
    parentIds: ["bartan"],
    name: { mn: "Есүхэй баатар", en: "Yesugei Baghatur" },
    title: "Боржигин язгууртан, баатар",
    years: "ойролцоо 1134-1171",
    rank: "khan",
    branch: "Хамаг Монгол",
    bio: "Тэмүжиний эцэг. Есүхэйн холбоо, дайсагнал нь Тэмүжинд бага наснаас нь тулгарсан хатуу улс төрийн орчныг тодорхойлсон.",
    achievements: ["Тал нутгийн холбоодыг хадгалсан", "Тэмүжиний язгуур эрхийг бататгасан"],
    capital: { name: "Онон голын сав нутаг", coordinates: [111.0, 48.8] },
  },
  {
    id: "genghis",
    parentIds: ["yesugei"],
    name: { mn: "Чингис хаан", en: "Genghis Khan / Temujin" },
    title: "Их Монгол Улсын Их хаан",
    years: "1162-1227",
    reign: "1206-1227",
    rank: "great-khan",
    branch: "Их Монгол Улс",
    bio: "Их Монгол Улсыг үндэслэгч. Тэмүжин 1206 онд Чингис хаан цол хүртэж, Евразийн түүхийг өөрчилсөн цэрэг-улс төрийн тогтолцоог байгуулсан.",
    achievements: [
      "1206 онд монгол аймгуудыг нэгтгэсэн",
      "Хишигтэн, аравтын цэргийн бүтэц, төрийн ёс хуулийн уламжлалыг бэхжүүлсэн",
      "Умард Хятад, Төв Ази, баруун тал нутаг руу их аян дайнуудыг эхлүүлсэн",
    ],
    capital: { name: "Аварга / Хэрлэнгийн бүс", coordinates: [110.6, 47.6] },
  },
  {
    id: "jochi",
    parentIds: ["genghis"],
    name: { mn: "Зүчи", en: "Jochi" },
    title: "Чингис хааны ууган хүү",
    years: "ойролцоо 1182-1227",
    rank: "prince",
    branch: "Зүчийн улс",
    bio: "Чингис хааны ууган хүү бөгөөд Зүчийн угсааны эхлэл. Түүний улс нь Бат хан болон залгамжлагчдын үед Алтан Ордны үндэс болсон.",
    achievements: ["Их улсын баруун нутгуудыг эзэмшсэн", "Зүчийн улсын угсаа залгамжлалын суурийг тавьсан"],
    capital: { name: "Зүчийн тал нутгийн улс", coordinates: [62.0, 48.0] },
  },
  {
    id: "chagatai",
    parentIds: ["genghis"],
    name: { mn: "Цагадай", en: "Chagatai" },
    title: "Чингис хааны хоёрдугаар хүү",
    years: "1183-1242",
    rank: "prince",
    branch: "Цагаадайн улс",
    bio: "Их хааны гэр бүл дотор хууль ёсны уламжлалыг чанд баримтлагч хэмээн танигдсан. Түүний үр сад Мавераннахр, Төв Азид Цагаадайн улсыг захирсан.",
    achievements: ["Төв Азийн улсыг эзэмшсэн", "Цагаадайн хаадын угсааны эх болсон"],
    capital: { name: "Алмалык орчим", coordinates: [80.8, 43.9] },
  },
  {
    id: "ogedei",
    parentIds: ["genghis"],
    name: { mn: "Өгэдэй", en: "Ogedei" },
    title: "Хоёрдугаар Их хаан",
    years: "1186-1241",
    reign: "1229-1241",
    rank: "great-khan",
    branch: "Өгэдэйн угсаа",
    bio: "Чингис хааны сонгосон залгамжлагч. Өгэдэй төрийн захиргааг өргөжүүлж, Хархорумыг их улсын бэлгэдлийн төв болгосон.",
    achievements: ["Их хаанаар төр барьсан", "Хархорумыг их улсын нийслэл болгон хөгжүүлсэн"],
    capital: { name: "Хархорум", coordinates: [102.84, 47.2] },
  },
  {
    id: "tolui",
    parentIds: ["genghis"],
    name: { mn: "Тулуй", en: "Tolui" },
    title: "Чингис хааны отгон хүү",
    years: "ойролцоо 1191-1232",
    rank: "prince",
    branch: "Тулуйн угсаа",
    bio: "Чингис хааны отгон хүү бөгөөд Монголын голомт нутгийг сахигч. Түүний үр сад хожмын их улсын хамгийн нөлөө бүхий хаадыг төрүүлсэн.",
    achievements: ["Монголын голомт нутгийг өвлөсөн", "Мөнх, Хубилай, Хүлэгү, Аригбөхийн эцэг болсон"],
    capital: { name: "Монголын голомт нутаг", coordinates: [103.6, 47.4] },
  },
  {
    id: "batu",
    parentIds: ["jochi"],
    name: { mn: "Бат хан", en: "Batu Khan" },
    title: "Алтан Ордны үндэслэгч",
    years: "ойролцоо 1205-1255",
    rank: "empire-founder",
    branch: "Алтан Орд",
    bio: "Чингис хааны ач, Алтан Ордны үндэслэгч. Бат хан Европын гүнд хүрсэн баруун зүгийн их аяныг удирдсан.",
    achievements: ["Баруун аяныг удирдсан", "Алтан Ордны улсыг үндэслэсэн"],
    capital: { name: "Сарай-Бат", coordinates: [47.7, 48.7] },
  },
  {
    id: "berke",
    parentIds: ["batu"],
    name: { mn: "Бэрх хан", en: "Berke Khan" },
    title: "Алтан Ордны хан",
    years: "?-1266",
    reign: "1257-1266",
    rank: "khan",
    branch: "Алтан Орд",
    bio: "Зүчийн угсааны хан. Алтан Ордны улс төр, шашны чиг хандлагад хүчтэй нөлөөлсөн.",
    achievements: ["Алтан Ордны бие даасан байдлыг бэхжүүлсэн"],
    capital: { name: "Сарай", coordinates: [47.8, 48.7] },
  },
  {
    id: "uzbeg",
    parentIds: ["berke"],
    name: { mn: "Өзбек хан", en: "Uzbeg Khan" },
    title: "Алтан Ордны хүчирхэг хан",
    years: "1282-1341",
    reign: "1313-1341",
    rank: "khan",
    branch: "Алтан Орд",
    bio: "Алтан Ордны хамгийн нөлөө бүхий хаадын нэг. Улсын дотоод нэгдэл, худалдаа, шашны бодлогыг бэхжүүлсэн.",
    achievements: ["Алтан Ордны оргил үеийг төлөөлсөн"],
    capital: { name: "Сарай", coordinates: [47.8, 48.7] },
  },
  {
    id: "toqtamysh",
    parentIds: ["uzbeg"],
    name: { mn: "Тохтамыш", en: "Tokhtamysh" },
    title: "Алтан Ордны сүүл үеийн хан",
    years: "ойролцоо 1342-1406",
    rank: "khan",
    branch: "Алтан Орд",
    bio: "Алтан Ордны нэгдлийг сэргээхийг оролдсон сүүл үеийн хүчирхэг хан.",
    achievements: ["Зүчийн улсын сүүл үеийн нэгдлийг сэргээхийг зорьсон"],
    capital: { name: "Сарай", coordinates: [47.8, 48.7] },
  },
  {
    id: "tsagadai-desc",
    parentIds: ["chagatai"],
    name: { mn: "Цагаадайн залгамж хаад", en: "Chagatai Successors" },
    title: "Цагаадайн улсын угсаа",
    years: "XIII-XIV зуун",
    rank: "khan",
    branch: "Цагаадайн улс",
    bio: "Цагаадайн үр сад Мавераннахр, Долоон ус, Төв Азийн улс төрд олон зуун жил нөлөөлсөн.",
    achievements: ["Төв Азийн Монгол угсааны төрүүдийг залгамжлуулсан"],
    capital: { name: "Алмалык / Самарканд", coordinates: [80.8, 43.9] },
  },
  {
    id: "kaidu-ogedeid",
    parentIds: ["ogedei"],
    name: { mn: "Хайду", en: "Kaidu" },
    title: "Өгэдэйн угсааны ноён",
    years: "1230-1301",
    rank: "khan",
    branch: "Өгэдэйн угсаа",
    bio: "Өгэдэйн угсааны хүчирхэг ноён. Хубилайн төвлөрсөн эрх мэдлийн эсрэг Төв Азид удаан тэмцсэн.",
    achievements: ["Өгэдэйн угсааны эрх мэдлийг хамгаалсан", "Төв Азийн улс төрд хүчтэй нөлөөлсөн"],
    capital: { name: "Төв Ази", coordinates: [76.9, 43.2] },
  },
  {
    id: "guyuk",
    parentIds: ["ogedei"],
    name: { mn: "Гүюг хаан", en: "Guyuk Khan" },
    title: "Гуравдугаар Их хаан",
    years: "1206-1248",
    reign: "1246-1248",
    rank: "great-khan",
    branch: "Өгэдэйн угсаа",
    bio: "Өгэдэйн хүү, гуравдугаар Их хаан. Түүний богино хаанчлал залгамжлалын тэмцэл болон өргөн уудам их улсыг нэгтгэн барих сорилтоор тодорхойлогдсон.",
    achievements: ["1246-1248 онд Их хаанаар төр барьсан", "Өгэдэйн угсааны эрх мэдлийг үргэлжлүүлсэн"],
    capital: { name: "Хархорум", coordinates: [102.84, 47.2] },
  },
  {
    id: "mongke",
    parentIds: ["tolui"],
    name: { mn: "Мөнх хаан", en: "Mongke Khan" },
    title: "Дөрөвдүгээр Их хаан",
    years: "1209-1259",
    reign: "1251-1259",
    rank: "great-khan",
    branch: "Тулуйн угсаа",
    bio: "Тулуйн угсааны Их хаан. Их улсын төв захиргааг сэргээж, баруун болон өмнөд аянуудыг идэвхжүүлсэн.",
    achievements: ["Их улсын захиргааг бэхжүүлсэн", "Хүлэгү, Хубилайн аянуудыг дэмжсэн"],
    capital: { name: "Хархорум", coordinates: [102.84, 47.2] },
  },
  {
    id: "hulagu",
    parentIds: ["tolui"],
    name: { mn: "Хүлэгү", en: "Hulagu Khan" },
    title: "Ил хаант улсын үндэслэгч",
    years: "ойролцоо 1217-1265",
    rank: "empire-founder",
    branch: "Ил хаант улс",
    bio: "Тулуйн угсааны хан хүү, Иранд Ил хаант улсыг үндэслэгч. Хүлэгүгийн аян дайн Ойрх Дорнодын түүхийг өөрчилсөн.",
    achievements: ["Ил хаант улсыг байгуулсан", "1258 онд Багдадыг эзэлсэн"],
    capital: { name: "Марага", coordinates: [46.24, 37.39] },
  },
  {
    id: "abaqa",
    parentIds: ["hulagu"],
    name: { mn: "Абага", en: "Abaqa Khan" },
    title: "Ил хаан",
    years: "1234-1282",
    reign: "1265-1282",
    rank: "khan",
    branch: "Ил хаант улс",
    bio: "Хүлэгүгийн залгамжлагч. Ил хаант улсын төрийн бүтцийг тогтворжуулахад чухал үүрэгтэй.",
    achievements: ["Ил хаант улсын залгамжлалыг бэхжүүлсэн"],
    capital: { name: "Тебриз", coordinates: [46.29, 38.08] },
  },
  {
    id: "ghazan",
    parentIds: ["abaqa"],
    name: { mn: "Газан хан", en: "Ghazan Khan" },
    title: "Ил хаант улсын шинэчлэгч",
    years: "1271-1304",
    reign: "1295-1304",
    rank: "khan",
    branch: "Ил хаант улс",
    bio: "Ил хаант улсын алдарт шинэчлэгч. Санхүү, засаг захиргаа, шашны бодлогод том өөрчлөлт хийсэн.",
    achievements: ["Ил хаант улсад шинэчлэл хийсэн"],
    capital: { name: "Тебриз", coordinates: [46.29, 38.08] },
  },
  {
    id: "abu-said",
    parentIds: ["ghazan"],
    name: { mn: "Абу Саид", en: "Abu Sa'id" },
    title: "Ил хаант улсын сүүл үеийн хан",
    years: "1305-1335",
    reign: "1316-1335",
    rank: "khan",
    branch: "Ил хаант улс",
    bio: "Ил хаант улсын сүүл үеийн чухал хаан. Түүний дараа Ил хаант улс олон хэсэгт задарсан.",
    achievements: ["Ил хаант улсын сүүл үеийг төлөөлсөн"],
    capital: { name: "Султания", coordinates: [48.8, 36.43] },
  },
  {
    id: "kublai",
    parentIds: ["tolui"],
    name: { mn: "Хубилай хаан", en: "Kublai Khan" },
    title: "Их хаан, Юань улсын эзэн хаан",
    years: "1215-1294",
    reign: "1260-1294",
    rank: "great-khan",
    branch: "Юань / Тулуйн угсаа",
    bio: "Тулуйн угсааны хаан, Их хаан бөгөөд Хятадад Юань улсыг үндэслэгч. Хубилай их улсын төвийг Зүүн Азид ойртуулсан.",
    achievements: ["Юань улсыг үндэслэсэн", "1279 онд Өмнөд Сүн улсыг бүрэн эзэлсэн"],
    capital: { name: "Дайду / Ханбалиг", coordinates: [116.4, 39.9] },
  },
  {
    id: "zhenjin",
    parentIds: ["kublai"],
    name: { mn: "Чингим", en: "Zhenjin" },
    title: "Юань улсын хан хүү",
    years: "1243-1286",
    rank: "prince",
    branch: "Юань",
    bio: "Хубилай хааны хүү, Юань улсын залгамжлагч хан хүү.",
    achievements: ["Юань улсын залгамжлалын гол шугамыг бүрдүүлсэн"],
    capital: { name: "Дайду", coordinates: [116.4, 39.9] },
  },
  {
    id: "temur-yuan",
    parentIds: ["zhenjin"],
    name: { mn: "Өлзийт Төмөр", en: "Temur Khan" },
    title: "Юань улсын эзэн хаан",
    years: "1265-1307",
    reign: "1294-1307",
    rank: "great-khan",
    branch: "Юань",
    bio: "Хубилайн залгамжлагч. Юань улсын засаг захиргааг тогтвортой хадгалсан.",
    achievements: ["Юань улсын залгамжлалыг бататгасан"],
    capital: { name: "Дайду", coordinates: [116.4, 39.9] },
  },
  {
    id: "toghon-temur",
    parentIds: ["temur-yuan"],
    name: { mn: "Тогоонтөмөр", en: "Toghon Temur" },
    title: "Юань улсын сүүлчийн эзэн хаан",
    years: "1320-1370",
    reign: "1333-1370",
    rank: "great-khan",
    branch: "Хойд Юань",
    bio: "Юань улсын Хятадад төр барьсан сүүлчийн эзэн хаан. 1368 оноос хойш Монгол нутагт Хойд Юань уламжлалыг үргэлжлүүлсэн.",
    achievements: ["Хойд Юань угсааны эхлэлийг тавьсан"],
    capital: { name: "Шанду / Монгол нутаг", coordinates: [116.0, 42.3] },
  },
  {
    id: "biligtu",
    parentIds: ["toghon-temur"],
    name: { mn: "Билигт хаан Аюушридар", en: "Biligtu Khan Ayushiridara" },
    title: "Хойд Юань хаан",
    years: "1340-1378",
    reign: "1370-1378",
    rank: "khan",
    branch: "Хойд Юань",
    bio: "Тогоонтөмөрийн залгамжлагч. Хойд Юань төрийг Монгол нутагт үргэлжлүүлсэн.",
    achievements: ["Хойд Юань төрийн залгамжлалыг хадгалсан"],
    capital: { name: "Монгол нутаг", coordinates: [105.0, 47.0] },
  },
  {
    id: "elbeg",
    parentIds: ["biligtu"],
    name: { mn: "Элбэг нигүүлсэгч хаан", en: "Elbeg Khan" },
    title: "Хойд Юань хаан",
    years: "1361-1399",
    reign: "1394-1399",
    rank: "khan",
    branch: "Хойд Юань",
    bio: "Хойд Юань улсын сүүл үеийн хаадын нэг. Дотоодын улс төрийн задрал гүнзгийрсэн цагт төр барьсан.",
    achievements: ["Хойд Юань угсааны залгамжлалд багтсан"],
    capital: { name: "Монгол нутаг", coordinates: [105.0, 47.0] },
  },
  {
    id: "ajai",
    parentIds: ["elbeg"],
    name: { mn: "Ажай тайж", en: "Ajai Taiji" },
    title: "Боржигин тайж",
    years: "XV зуун",
    rank: "prince",
    branch: "Хойд Юань",
    bio: "Даян хааны өмнөх Боржигин шугамын чухал холбоос хэмээн угсааны бичигт дурдагддаг.",
    achievements: ["Даян хааны угсааны өмнөх холбоос болсон"],
    capital: { name: "Монгол нутаг", coordinates: [105.0, 47.0] },
  },
  {
    id: "bayanmongke",
    parentIds: ["ajai"],
    name: { mn: "Баянмөнх жонон", en: "Bayanmongke Jonon" },
    title: "Жонон, Даян хааны эцэг",
    years: "XV зуун",
    rank: "prince",
    branch: "Даян хааны шугам",
    bio: "Даян хааны эцэг. Монголын төрийн нэгдлийг сэргээх угсааны гол холбоос.",
    achievements: ["Даян хааны шууд угсааны эх болсон"],
    capital: { name: "Монгол нутаг", coordinates: [105.3, 46.9] },
  },
  {
    id: "dayan",
    parentIds: ["bayanmongke"],
    name: { mn: "Даян хаан", en: "Dayan Khan" },
    title: "Монголын нэгдлийг сэргээсэн хаан",
    years: "1464-1543",
    reign: "1479-1543",
    rank: "revival",
    branch: "Даян хааны сэргэлт",
    bio: "Даян хаан бутарсан Монгол аймгуудыг дахин нэгтгэж, Зүүн Монголын төрийн бүтцийг сэргээсэн. Түүний үр сад Халх, Цахар, Ордос, Түмэд зэрэг олон шугамд тархсан.",
    achievements: ["Монголын улс төрийн нэгдлийг сэргээсэн", "Зургаан түмний зохион байгуулалтыг бэхжүүлсэн"],
    capital: { name: "Зүүн Монгол", coordinates: [108.5, 45.8] },
  },
  {
    id: "barsbolod",
    parentIds: ["dayan"],
    name: { mn: "Барсболд жонон", en: "Barsbolod Jonon" },
    title: "Жонон, Даян хааны хүү",
    years: "1484-1531",
    rank: "prince",
    branch: "Цахар / Түмэдийн холбоос",
    bio: "Даян хааны хүү. Түүний үр сад Монголын олон аймаг, түмний улс төрд хүчтэй нөлөөлсөн.",
    achievements: ["Даян хааны дараах салбаруудын гол өвөг болсон"],
    capital: { name: "Зүүн Монгол", coordinates: [108.5, 45.8] },
  },
  {
    id: "bodialag",
    parentIds: ["dayan"],
    name: { mn: "Боди-Алаг хаан", en: "Bodi Alagh Khan" },
    title: "Монголын хаан",
    years: "1504-1547",
    reign: "1524-1547",
    rank: "khan",
    branch: "Хойд Юань",
    bio: "Даян хааны залгамжлагчдын нэг. Даян хааны байгуулсан нэгдлийн дараах төрийн тогтолцоог үргэлжлүүлсэн.",
    achievements: ["Хойд Юань хаадын залгамжлалыг үргэлжлүүлсэн"],
    capital: { name: "Цахар", coordinates: [113.0, 42.0] },
  },
  {
    id: "altan-khan",
    parentIds: ["barsbolod"],
    name: { mn: "Алтан хан", en: "Altan Khan of Tumed" },
    title: "Түмэдийн Алтан хан",
    years: "1507-1582",
    rank: "khan",
    branch: "Түмэд",
    bio: "Даян хааны ач, Түмэдийн алдарт хан. Хот суурин, худалдаа, шашин соёлын харилцаанд том нөлөө үзүүлсэн.",
    achievements: ["Түмэдийн хүчийг өсгөсөн", "Далай ламын цолыг өргөсөн уламжлалтай холбогддог"],
    capital: { name: "Хөх хот орчим", coordinates: [111.7, 40.8] },
  },
  {
    id: "tumen-zasagt",
    parentIds: ["bodialag"],
    name: { mn: "Түмэн засагт хаан", en: "Tumen Zasagt Khan" },
    title: "Монголын хаан",
    years: "1539-1592",
    reign: "1558-1592",
    rank: "khan",
    branch: "Цахар",
    bio: "Зүүн Монголын төрийн залгамжлалыг үргэлжлүүлсэн хаан.",
    achievements: ["Цахарын хаадын эрх мэдлийг хадгалсан"],
    capital: { name: "Цахар", coordinates: [113.0, 42.0] },
  },
  {
    id: "buyan-sechen",
    parentIds: ["tumen-zasagt"],
    name: { mn: "Буян сэцэн хаан", en: "Buyan Sechen Khan" },
    title: "Монголын хаан",
    years: "1554-1603",
    reign: "1592-1603",
    rank: "khan",
    branch: "Цахар",
    bio: "Түмэн засагтын залгамжлагч, Цахарын хаадын шугамыг Лигдэн хаан руу холбосон.",
    achievements: ["Лигдэн хааны өмнөх Цахарын хаадын шугамыг хадгалсан"],
    capital: { name: "Цахар", coordinates: [113.0, 42.0] },
  },
  {
    id: "ligdan",
    parentIds: ["buyan-sechen"],
    name: { mn: "Лигдэн хаан", en: "Ligdan Khan" },
    title: "Хойд Юань улсын сүүлчийн их хаан",
    years: "1588-1634",
    reign: "1604-1634",
    rank: "great-khan",
    branch: "Цахар / Хойд Юань",
    bio: "Лигдэн хаан Хойд Юань улсын сүүлчийн их хаан гэж тооцогддог. Манжийн өсөлт, Монголын дотоод задралын үед Чингисийн төрийн эрх мэдлийг сэргээхийг оролдсон.",
    achievements: ["Хойд Юань улсын сүүлчийн их хаан болсон", "Монголын төв эрх мэдлийг дахин нэгтгэхийг зорьсон"],
    capital: { name: "Цахар", coordinates: [113.0, 42.0] },
  },
  {
    id: "tusheet-khan-final",
    parentIds: ["dayan"],
    name: { mn: "Навааннэрэн Түшээт хан", en: "Navaanneren Tusheet Khan" },
    title: "Халхын Түшээт хан аймгийн сүүл үеийн хан",
    years: "1877-1937",
    reign: "XX зууны эхэн",
    rank: "final-head",
    branch: "Халхын Түшээт хан аймаг",
    bio: "1924 оны Бүгд Найрамдах засаглал тогтох хүртэл уламжлалт хан аймгийн толгой ноёдын нэгэн төлөөлөл.",
    achievements: ["Халхын хан аймгийн сүүл үеийг төлөөлсөн"],
    capital: { name: "Түшээт хан аймаг", coordinates: [106.9, 47.9] },
  },
  {
    id: "setsen-khan-final",
    parentIds: ["dayan"],
    name: { mn: "Навааннэрэн Сэцэн хан", en: "Navaanneren Setsen Khan" },
    title: "Халхын Сэцэн хан аймгийн сүүл үеийн хан",
    years: "XIX-XX зуун",
    rank: "final-head",
    branch: "Халхын Сэцэн хан аймаг",
    bio: "1924 он хүртэлх уламжлалт Халхын дөрвөн аймгийн нэг болох Сэцэн хан аймгийн сүүл үеийн төлөөлөх толгой.",
    achievements: ["Сэцэн хан аймгийн сүүл үеийг төлөөлсөн"],
    capital: { name: "Сэцэн хан аймаг", coordinates: [110.6, 47.3] },
  },
  {
    id: "zasagt-khan-final",
    parentIds: ["dayan"],
    name: { mn: "Содномравдан Засагт хан", en: "Sodnomravdan Zasagt Khan" },
    title: "Халхын Засагт хан аймгийн сүүл үеийн хан",
    years: "XIX-XX зуун",
    rank: "final-head",
    branch: "Халхын Засагт хан аймаг",
    bio: "Халхын баруун талын Засагт хан аймгийн сүүл үеийн язгууртны төлөөлөл.",
    achievements: ["Засагт хан аймгийн уламжлалт засаглалыг төлөөлсөн"],
    capital: { name: "Засагт хан аймаг", coordinates: [96.9, 47.9] },
  },
  {
    id: "sain-noyon-final",
    parentIds: ["dayan"],
    name: { mn: "Цэрэндорж Сайн ноён хан", en: "Tserendorj Sain Noyon Khan" },
    title: "Сайн ноён хан аймгийн сүүл үеийн хан",
    years: "XIX-XX зуун",
    rank: "final-head",
    branch: "Сайн ноён хан аймаг",
    bio: "1924 он хүртэлх Халхын дөрвөн аймгийн нэг болох Сайн ноён хан аймгийн сүүл үеийн төлөөлөх толгой.",
    achievements: ["Сайн ноён хан аймгийн сүүл үеийг төлөөлсөн"],
    capital: { name: "Сайн ноён хан аймаг", coordinates: [102.8, 46.3] },
  },
];

export const altanUragEdges = altanUragPeople.flatMap((person) =>
  person.parentIds.map((parentId) => ({
    id: `${parentId}-${person.id}`,
    source: parentId,
    target: person.id,
  })),
);
