import type { AtlasStateRecord } from "@/lib/types";
import { rings } from "@/lib/seed-rings";

export const atlasSeedDataAPart2: AtlasStateRecord[] = [
    {
    slug: "qara-khitai",
    year: 1189,
    name: "Хар Хятан",
    leader: "Елюй Жилүгү",
    capital: "Баласагун",
    color: "#0f766e",
    summary: "Хар Хятан Төв Азийн тэнцвэрийн хүчин хэвээр үлдэж, баруун зүгт Хорезмтэй, зүүн зүгт Уйгур, Наймантай холбогдож байв.",
    metadata: {
      governance: "Вассал төвтэй эзэн хаант бүтэц",
      notableEvents: ["Жетисугийн худалдааны гарцыг хянав"],
    },
    geometry: rings.qaraKhitai,
  },
    {
    slug: "great-mongol-state",
    year: 1206,
    name: "Их Монгол Улс",
    leader: "Чингис хаан",
    capital: "Хэрлэнгийн ордон",
    color: "#c9a45d",
    summary: "1206 оны их хуралдайгаар Чингис хаан бүх Монголыг нэгтгэн Их Монгол Улсыг байгуулж, арвантын тогтолцоо, шинэ захиргааны үндсийг тавив.",
    metadata: {
      periodName: "Yeke Mongghol Ulus",
      culture: "Нүүдэлчин цэргийн төр",
      religion: "Тэнгэр шүтлэг",
      economy: "Мал аж ахуй, олз, хараат аймгийн алба",
      military: "Арвант, зуут, мянгат, түмтэд тулгуурласан морьт арми",
      governance: "Хааны төвлөрсөн засаглал",
      strategicFocus: "Тал нутгийг бат тогтоон, хөрш улсууд руу нэвтрэх гарц нээх",
      notableEvents: ["1206 оны их хуралдай", "Цэргийн шинэчилсэн зохион байгуулалт"],
    },
    geometry: rings.greatMongol1206,
  },
    {
    slug: "jin-dynasty",
    year: 1206,
    name: "Алтан улс",
    leader: "Вэйшао вангийн ордон",
    capital: "Жүндү",
    color: "#d97706",
    summary: "Алтан улс Монголын нэгдлийг үл тоомсорлож болохгүйг мэдэрч байсан ч умард Хятадын өргөн бүсэд ноёрхлоо хадгалсаар байв.",
    metadata: {
      governance: "Ордны бюрократ бүтэц",
      military: "Хэрмийн гарнизон ба морьт анги",
      notableEvents: ["Хилийн дипломат хурцадмал байдал"],
    },
    geometry: rings.jin,
  },
    {
    slug: "western-xia",
    year: 1206,
    name: "Баруун Ся",
    leader: "Сянзун",
    capital: "Шинчин",
    color: "#92400e",
    summary: "Баруун Ся шинэ Монголын улсыг ажиглаж, худалдаа ба хил хамгаалалтаа зэрэг хамгаалахыг оролдож байв.",
    metadata: {
      strategicFocus: "Монгол, Алтан хоёрын дунд амьд үлдэх тэнцвэр",
      notableEvents: ["Ганьсугийн коридорын хамгаалалт"],
    },
    geometry: rings.westernXia,
  },
    {
    slug: "khwarazm",
    year: 1206,
    name: "Хорезм",
    leader: "Ала ад-Дин Мухаммед",
    capital: "Гүрганж",
    color: "#16a34a",
    summary: "Хорезм шахын улс Төв Азийн худалдааны томоохон гүрэн болон өсөж, Иран, Мавераннахр, Аралын орчмыг холбож байв.",
    metadata: {
      religion: "Ислам",
      economy: "Хот суурин, тариалан, торгоны замын худалдаа",
      military: "Хотын гарнизон ба хүнд морьт анги",
      governance: "Шахын төвлөрсөн засаг",
      notableEvents: ["Төв Азийн худалдааны зангилаанд хүчирхэгжив"],
    },
    geometry: rings.khwarazm,
  },
    {
    slug: "uighur-idiqut",
    year: 1206,
    name: "Уйгурын Идигүд улс",
    leader: "Бархүчүк",
    capital: "Бешбалык",
    color: "#eab308",
    summary: "Таримын сав, Турфаны хонгилыг түшсэн Уйгурын улс нь Монголчуудтай дипломат ойртолт хийх ирээдүйн суурийг тавьж байв.",
    metadata: {
      culture: "Уйгур бичиг, хот суурингийн соёл",
      religion: "Буддизм, манихей, несториан урсгалын нөлөө",
      economy: "Оазисын худалдаа",
      notableEvents: ["Турфаны зангилаа бүсийг хянав"],
    },
    geometry: rings.uighur,
  },
];
