import type { AtlasStateRecord } from "@/lib/types";
import { polygon, rings } from "@/lib/seed-rings";

export const atlasSeedDataBPart1: AtlasStateRecord[] = [
    {
    slug: "great-mongol-state",
    year: 1211,
    name: "Их Монгол Улс",
    leader: "Чингис хаан",
    capital: "Аварга ордон",
    color: "#c9a45d",
    summary: "1211 онд Чингис хаан Алтан улсын эсрэг томоохон довтолгоо эхлүүлж, умард Хятадын хаалгыг нээв.",
    metadata: {
      periodName: "Yeke Mongghol Ulus",
      military: "Түмт түшсэн довтолгооны арми",
      strategicFocus: "Алтан улсын хойд хамгаалалтыг нэвтрэх",
      notableEvents: ["Ехулиний хавцлын тулааны өмнөх давшилт", "Алтан улс руу анхны системтэй аян"],
    },
    geometry: rings.mongol1215,
  },
    {
    slug: "jin-dynasty",
    year: 1211,
    name: "Алтан улс",
    leader: "Вэйшаовань Юнжи",
    capital: "Жүндү",
    color: "#d97706",
    summary: "Монголын довтолгоо Алтан улсын умард хилийн хамгаалалтын эмзэг байдлыг ил болгов.",
    metadata: {
      military: "Цайз хэрэмд түшсэн хамгаалалт",
      notableEvents: ["Монголчууд Цагаан хэрмийн шугамыг давж эхлэв"],
    },
    geometry: rings.jin,
  },
    {
    slug: "western-xia",
    year: 1211,
    name: "Баруун Ся",
    leader: "Шэньцзун",
    capital: "Шинчин",
    color: "#92400e",
    summary: "Баруун Ся Монгол, Алтан улсын дайны дунд шахагдаж, вассалын дарамтад орж эхлэв.",
    metadata: {
      strategicFocus: "Өөрийгөө довтолгооноос хамгаалах",
      notableEvents: ["Монголын нөлөөнд шахагдав"],
    },
    geometry: rings.westernXia,
  },
    {
    slug: "uighur-idiqut",
    year: 1211,
    name: "Уйгурын Идигүд улс",
    leader: "Бархүчүк",
    capital: "Бешбалык",
    color: "#eab308",
    summary: "Уйгурын Идигүд улс Монголтой албан ёсоор ойртож, бичиг захиргаа, орчуулагчийн нөөцөөрөө чухал түнш болж эхлэв.",
    metadata: {
      governance: "Хот суурин түшсэн вант улс",
      notableEvents: ["Монголын гол холбоотны нэг болов"],
    },
    geometry: rings.uighur,
  },
    {
    slug: "great-mongol-state",
    year: 1215,
    name: "Их Монгол Улс",
    leader: "Чингис хаан",
    capital: "Аварга ордон",
    color: "#c9a45d",
    summary: "1215 онд Монголчууд Жүндүг эзэлж, Алтан улсын хойд захиргааг цөмлөн, Хойд Хятадын улстөрийн тэнцвэрийг эрс өөрчиллөө.",
    metadata: {
      periodName: "Yeke Mongghol Ulus",
      military: "Бүсэлгээ, сэтгэлзүйн дайн, хурдан нүүдэл",
      strategicFocus: "Алтан улсын төвийг задлах",
      notableEvents: ["Жүндү хотын эзлэлт"],
    },
    geometry: rings.mongol1215,
  },
    {
    slug: "jin-dynasty",
    year: 1215,
    name: "Алтан улсын үлдэгдэл",
    leader: "Сюаньзун",
    capital: "Кайфэн",
    color: "#b45309",
    summary: "Жүндүг алдаад өмнө зүг рүү ухарсан Алтан улс Монголын дарамтад орсон ч бүрэн мөхөөгүй байв.",
    metadata: {
      governance: "Шилжин байрласан ордон",
      notableEvents: ["Нийслэлээ өмнө тийш шилжүүлэв"],
    },
    geometry: polygon([
      [108, 38],
      [114, 39],
      [121, 38],
      [123, 34],
      [118, 31],
      [111, 31.5],
      [107.5, 34],
      [108, 38],
    ]),
  },
    {
    slug: "khwarazm",
    year: 1215,
    name: "Хорезм",
    leader: "Ала ад-Дин Мухаммед",
    capital: "Гүрганж",
    color: "#16a34a",
    summary: "Хорезм шахын улс баруун Төв Азид оргил хүчээ авч, удалгүй Монголын анхааралд өртөх ирмэг дээр ирэв.",
    metadata: {
      strategicFocus: "Худалдааны урсгалыг хянах",
      notableEvents: ["Самарканд, Бухарын бүс дэх нөлөө өсөв"],
    },
    geometry: rings.khwarazm,
  },
    {
    slug: "uighur-idiqut",
    year: 1215,
    name: "Уйгурын Идигүд улс",
    leader: "Бархүчүк",
    capital: "Бешбалык",
    color: "#eab308",
    summary: "Монголын холбоотон болсон Уйгурын Идигүд улс захиргааны туршлага, бичгийн соёлоороо шинэ эзэнт гүрэнд чухал үүрэгтэй болов.",
    metadata: {
      notableEvents: ["Монгол төрийн бичгийн хэрэгт оролцов"],
    },
    geometry: rings.uighur,
  },
];
