INSERT INTO atlas_events (
  slug,
  start_year,
  end_year,
  title,
  description,
  event_type,
  related_states,
  coordinates,
  metadata
)
VALUES
(
  'merkit-campaign-1184',
  1184,
  1184,
  'Campaign against the Merkits',
  'Temujin, with support from allies, attacked the Merkits after they kidnapped Börte. This was one of the early military events that strengthened Temujin’s position among the Mongol tribes.',
  'campaign',
  ARRAY['khamag-mongol'],
  '[109.0, 48.0]'::jsonb,
  '{"icon": "⚔", "label": "1184 · Merkit Campaign", "importance": "medium"}'::jsonb
),
(
  'dalan-balzhut-1187',
  1187,
  1187,
  'Battle of Dalan Balzhut',
  'An early conflict between Temujin and Jamukha. Although Temujin was defeated, the event became part of the long struggle for leadership among the Mongol tribes.',
  'battle',
  ARRAY['khamag-mongol'],
  '[111.0, 48.0]'::jsonb,
  '{"icon": "⚔", "label": "1187 · Dalan Balzhut", "importance": "medium"}'::jsonb
),
(
  'koyiten-1201',
  1201,
  1201,
  'Battle of Koyiten',
  'Temujin and his allies fought against a coalition of rival steppe groups. The victory helped Temujin weaken his enemies and move closer to unifying the Mongol tribes.',
  'battle',
  ARRAY['khamag-mongol'],
  '[108.6, 47.5]'::jsonb,
  '{"icon": "⚔", "label": "1201 · Koyiten", "importance": "high"}'::jsonb
),
(
  'keraite-campaign-1203',
  1203,
  1203,
  'Campaign against the Keraites',
  'Temujin defeated the Keraites, one of the strongest powers on the Mongolian steppe. This campaign removed a major rival and expanded Temujin’s authority.',
  'campaign',
  ARRAY['khamag-mongol'],
  '[107.5, 47.3]'::jsonb,
  '{"icon": "⚔", "label": "1203 · Keraite Campaign", "importance": "high"}'::jsonb
),
(
  'naiman-campaign-1204',
  1204,
  1204,
  'Campaign against the Naimans',
  'Temujin defeated the Naimans, another powerful steppe confederation. This victory helped complete the unification of the Mongol tribes before the foundation of the Mongol Empire.',
  'campaign',
  ARRAY['khamag-mongol'],
  '[92.0, 48.0]'::jsonb,
  '{"icon": "⚔", "label": "1204 · Naiman Campaign", "importance": "high"}'::jsonb
),
(
  'great-kurultai-1206',
  1206,
  1206,
  'Great Kurultai of 1206',
  'Temujin was proclaimed Chinggis Khan, and the Mongol tribes were united under one supreme ruler. This marked the foundation of the Great Mongol State.',
  'political',
  ARRAY['great-mongol-state', 'khamag-mongol'],
  '[109.0, 47.7]'::jsonb,
  '{"icon": "★", "label": "1206 · Great Kurultai", "importance": "very_high"}'::jsonb
),
(
  'western-xia-raids-1205-1209',
  1205,
  1209,
  'Early Campaigns against Western Xia',
  'The Mongols launched repeated campaigns against Western Xia. These campaigns tested Mongol siege and campaign strategy against settled states.',
  'campaign',
  ARRAY['great-mongol-state', 'western-xia'],
  '[106.2493, 38.4888]'::jsonb,
  '{"icon": "⚔", "label": "1205–1209 · Western Xia", "importance": "high"}'::jsonb
),
(
  'jin-campaign-1211-1215',
  1211,
  1215,
  'Mongol Campaign against the Jin Dynasty',
  'Chinggis Khan launched a major campaign against the Jin dynasty in North China. The campaign led to the capture of Zhongdu and greatly weakened Jin power.',
  'war',
  ARRAY['mongol-empire', 'jin-dynasty'],
  '[116.4074, 39.9042]'::jsonb,
  '{"icon": "⚔", "label": "1211–1215 · Jin War", "importance": "very_high"}'::jsonb
),
(
  'zhongdu-1215',
  1215,
  1215,
  'Capture of Zhongdu',
  'Mongol forces captured Zhongdu, the Jin capital. This was a major victory in the Mongol war against the Jin dynasty.',
  'battle',
  ARRAY['mongol-empire', 'jin-dynasty'],
  '[116.4074, 39.9042]'::jsonb,
  '{"icon": "⚔", "label": "1215 · Zhongdu", "importance": "high"}'::jsonb
),
(
  'qara-khitai-campaign-1218',
  1218,
  1218,
  'Campaign against Qara Khitai',
  'Mongol forces under Jebe moved into Central Asia and helped bring an end to Qara Khitai power. This opened the way toward the Khwarazmian frontier.',
  'campaign',
  ARRAY['mongol-empire', 'qara-khitai'],
  '[75.2486, 42.7469]'::jsonb,
  '{"icon": "⚔", "label": "1218 · Qara Khitai", "importance": "high"}'::jsonb
),
(
  'khwarazm-campaign-1219-1221',
  1219,
  1221,
  'Mongol Campaign against Khwarazm',
  'After conflict with the Khwarazmian Empire, Chinggis Khan launched a massive campaign into Central Asia. This became one of the most important Mongol conquests.',
  'war',
  ARRAY['mongol-empire', 'khwarazm'],
  '[64.5, 39.7]'::jsonb,
  '{"icon": "⚔", "label": "1219–1221 · Khwarazm", "importance": "very_high"}'::jsonb
),
(
  'otrar-1219',
  1219,
  1219,
  'Siege of Otrar',
  'Otrar was one of the first major targets in the Mongol campaign against Khwarazm. The siege became a symbolic beginning of the war.',
  'battle',
  ARRAY['mongol-empire', 'khwarazm'],
  '[68.3, 42.85]'::jsonb,
  '{"icon": "⚔", "label": "1219 · Otrar", "importance": "high"}'::jsonb
),
(
  'bukhara-1220',
  1220,
  1220,
  'Capture of Bukhara',
  'Mongol forces captured Bukhara during the Khwarazm campaign. The city was an important urban and religious center in Central Asia.',
  'battle',
  ARRAY['mongol-empire', 'khwarazm'],
  '[64.43, 39.77]'::jsonb,
  '{"icon": "⚔", "label": "1220 · Bukhara", "importance": "high"}'::jsonb
),
(
  'samarkand-1220',
  1220,
  1220,
  'Capture of Samarkand',
  'Samarkand, one of the greatest cities of the Khwarazmian Empire, fell to Mongol forces during the Central Asian campaign.',
  'battle',
  ARRAY['mongol-empire', 'khwarazm'],
  '[66.97, 39.65]'::jsonb,
  '{"icon": "⚔", "label": "1220 · Samarkand", "importance": "high"}'::jsonb
),
(
  'gurganj-1221',
  1221,
  1221,
  'Siege of Gurganj',
  'Gurganj, an important Khwarazmian city, was captured after a difficult siege. It was one of the harshest urban battles of the campaign.',
  'battle',
  ARRAY['mongol-empire', 'khwarazm'],
  '[59.15, 42.3167]'::jsonb,
  '{"icon": "⚔", "label": "1221 · Gurganj", "importance": "high"}'::jsonb
),
(
  'indus-1221',
  1221,
  1221,
  'Battle near the Indus River',
  'Chinggis Khan pursued Jalal ad-Din toward the Indus River. The battle marked the final stage of the Khwarazm campaign.',
  'battle',
  ARRAY['mongol-empire', 'khwarazm', 'delhi-sultanate'],
  '[70.0, 32.0]'::jsonb,
  '{"icon": "⚔", "label": "1221 · Indus", "importance": "medium"}'::jsonb
),
(
  'kalka-1223',
  1223,
  1223,
  'Battle of the Kalka River',
  'Mongol forces defeated a coalition of Rus and Cuman forces near the Kalka River. This battle showed Mongol power reaching into the western steppe.',
  'battle',
  ARRAY['mongol-empire', 'golden-horde-frontier'],
  '[37.5, 47.1]'::jsonb,
  '{"icon": "⚔", "label": "1223 · Kalka River", "importance": "high"}'::jsonb
),
(
  'western-xia-final-1226-1227',
  1226,
  1227,
  'Final Campaign against Western Xia',
  'Chinggis Khan led a final campaign against Western Xia. The campaign ended with the fall of Western Xia and occurred near the end of Chinggis Khan’s life.',
  'war',
  ARRAY['mongol-empire', 'western-xia'],
  '[106.2493, 38.4888]'::jsonb,
  '{"icon": "⚔", "label": "1226–1227 · Western Xia", "importance": "very_high"}'::jsonb
),
(
  'mongol-western-campaign-1236-1242',
  1236,
  1242,
  'Mongol Western Campaign',
  'After Chinggis Khan, Mongol armies under Batu and Subutai advanced westward into the Rus lands and Europe. This campaign led to the rise of the Golden Horde.',
  'war',
  ARRAY['golden-horde', 'mongol-empire'],
  '[37.6, 55.8]'::jsonb,
  '{"icon": "⚔", "label": "1236–1242 · Western Campaign", "importance": "very_high"}'::jsonb
),
(
  'kiev-1240',
  1240,
  1240,
  'Capture of Kiev',
  'Mongol forces captured Kiev during the western campaign. This was a major event in the Mongol expansion into Eastern Europe.',
  'battle',
  ARRAY['golden-horde', 'mongol-empire'],
  '[30.5234, 50.4501]'::jsonb,
  '{"icon": "⚔", "label": "1240 · Kiev", "importance": "high"}'::jsonb
),
(
  'legnica-1241',
  1241,
  1241,
  'Battle of Legnica',
  'Mongol forces defeated a European coalition in Poland during the western campaign.',
  'battle',
  ARRAY['golden-horde', 'mongol-empire'],
  '[16.1619, 51.2070]'::jsonb,
  '{"icon": "⚔", "label": "1241 · Legnica", "importance": "high"}'::jsonb
),
(
  'mohi-1241',
  1241,
  1241,
  'Battle of Mohi',
  'Mongol forces defeated the Kingdom of Hungary at Mohi. It was one of the largest battles of the Mongol invasion of Europe.',
  'battle',
  ARRAY['golden-horde', 'mongol-empire'],
  '[20.8, 47.7]'::jsonb,
  '{"icon": "⚔", "label": "1241 · Mohi", "importance": "high"}'::jsonb
),
(
  'alamut-1256',
  1256,
  1256,
  'Capture of Alamut',
  'Hulagu’s campaign led to the capture of Alamut, a major stronghold in Iran. This was part of the Mongol expansion into the Middle East.',
  'battle',
  ARRAY['ilkhanate', 'mongol-empire'],
  '[50.99, 36.45]'::jsonb,
  '{"icon": "⚔", "label": "1256 · Alamut", "importance": "high"}'::jsonb
),
(
  'baghdad-1258',
  1258,
  1258,
  'Siege of Baghdad',
  'Mongol forces under Hulagu captured Baghdad. This event marked the end of the Abbasid Caliphate and was one of the most significant Mongol victories in the Middle East.',
  'battle',
  ARRAY['ilkhanate', 'mamluk-sultanate'],
  '[44.3661, 33.3152]'::jsonb,
  '{"icon": "⚔", "label": "1258 · Baghdad", "importance": "very_high"}'::jsonb
),
(
  'ain-jalut-1260',
  1260,
  1260,
  'Battle of Ain Jalut',
  'The Mamluks defeated Mongol forces at Ain Jalut. This battle stopped further Mongol expansion into Egypt.',
  'battle',
  ARRAY['ilkhanate', 'mamluk-sultanate'],
  '[35.3, 32.6]'::jsonb,
  '{"icon": "⚔", "label": "1260 · Ain Jalut", "importance": "very_high"}'::jsonb
),
(
  'yuan-song-war-1271-1279',
  1271,
  1279,
  'Yuan Campaign against the Song Dynasty',
  'Kublai Khan’s Yuan forces continued the conquest of the Southern Song. The campaign ended with the fall of the Song dynasty.',
  'war',
  ARRAY['yuan-dynasty', 'song-dynasty', 'mongol-empire'],
  '[120.1551, 30.2741]'::jsonb,
  '{"icon": "⚔", "label": "1271–1279 · Song Campaign", "importance": "very_high"}'::jsonb
),
(
  'first-japan-invasion-1274',
  1274,
  1274,
  'First Mongol Invasion of Japan',
  'Yuan forces launched the first invasion of Japan. The campaign failed after resistance and severe weather.',
  'campaign',
  ARRAY['yuan-dynasty'],
  '[130.4, 33.6]'::jsonb,
  '{"icon": "⚔", "label": "1274 · Japan Invasion", "importance": "high"}'::jsonb
),
(
  'yamen-1279',
  1279,
  1279,
  'Battle of Yamen',
  'The Yuan dynasty defeated the last Song forces at Yamen, completing the conquest of the Southern Song.',
  'battle',
  ARRAY['yuan-dynasty', 'song-dynasty'],
  '[113.1, 22.2]'::jsonb,
  '{"icon": "⚔", "label": "1279 · Yamen", "importance": "very_high"}'::jsonb
),
(
  'second-japan-invasion-1281',
  1281,
  1281,
  'Second Mongol Invasion of Japan',
  'The Yuan dynasty launched a second invasion of Japan. The campaign failed after strong resistance and destructive storms.',
  'campaign',
  ARRAY['yuan-dynasty'],
  '[130.4, 33.6]'::jsonb,
  '{"icon": "⚔", "label": "1281 · Japan Invasion", "importance": "high"}'::jsonb
),
(
  'wadi-al-khaznadar-1299',
  1299,
  1299,
  'Battle of Wadi al-Khaznadar',
  'Ilkhanate forces defeated the Mamluks in Syria. This was one of the late major Mongol victories against the Mamluk Sultanate before 1300.',
  'battle',
  ARRAY['ilkhanate', 'mamluk-sultanate'],
  '[36.2, 34.9]'::jsonb,
  '{"icon": "⚔", "label": "1299 · Wadi al-Khaznadar", "importance": "medium"}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  start_year = EXCLUDED.start_year,
  end_year = EXCLUDED.end_year,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  related_states = EXCLUDED.related_states,
  coordinates = EXCLUDED.coordinates,
  metadata = EXCLUDED.metadata;